// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public struct Boundary
{
	public float left;
	public float bottom;
	public float right;
	public float top;
	public float width;
	public float height;

	public Boundary(float l, float b, float r, float t)
	{
		left = l;
		bottom = b;
		right = r;
		top = t;
		width = right - left;
		height = top - bottom;
	}
}


